name: metronome_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  assets_audio_player: ^3.1.1
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_riverpod: ^2.4.4
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  go_router: ^12.0.0
  go_router_builder: ^2.3.3
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.8
  riverpod_annotation: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.8
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.6

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon_minus.svg
    - assets/icons/icon_plus.svg
    - assets/icons/icon_note.svg
    - assets/images/main_page_background.jpg
    - assets/images/auth_page_background.jpg
    - assets/images/logo.png
    - assets/audio/pno_m.mp3
    - assets/audio/pno_s.mp3


